run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (io.Closer).Close
      - fmt.Fprintln
      - fmt.Fprintf

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
  max-issues-per-linter: 0
  max-same-issues: 0
